- expansion: 1
  out_channels: 16
  num_blocks: 1
  stride: 1
- expansion: 6
  out_channels: 24
  num_blocks: 2
  stride: 1
- expansion: 6
  out_channels: 32
  num_blocks: 3
  stride: 2
- expansion: 6
  out_channels: 64
  num_blocks: 4
  stride: 2
- expansion: 6
  out_channels: 96
  num_blocks: 3
  stride: 1
- expansion: 6
  out_channels: 160
  num_blocks: 3
  stride: 2
- expansion: 6
  out_channels: 320
  num_blocks: 1
  stride: 1